// MPL-2.0. Save/switch at the original UIKit run-loop boundary.
use crate::{msg,msg_class,Environment};
use crate::objc::{id,nil};
use serde_json::{json,Value};
use std::sync::{Mutex,OnceLock,atomic::{AtomicBool,Ordering}};
static REQUEST:OnceLock<Mutex<Option<String>>>=OnceLock::new();
static BUSY:AtomicBool=AtomicBool::new(false);
fn pending()->&'static Mutex<Option<String>>{REQUEST.get_or_init(||Mutex::new(None))}
pub fn request(action:&str){*pending().lock().unwrap()=Some(action.into());}
fn root()->std::path::PathBuf{std::env::var_os("ZF_HOME").map(Into::into).unwrap_or_else(||crate::desktop_mods::data_dir().parent().unwrap().to_owned())}
fn registry()->Value{std::fs::read(root().join("farms.json")).ok().and_then(|b|serde_json::from_slice(&b).ok()).unwrap_or(Value::Null)}
pub fn active_name()->String{let r=registry();let id=r["active"].as_u64().unwrap_or(1);format!("Farm {id}")}
pub fn rows()->Vec<(String,String)>{let r=registry();let active=r["active"].as_u64().unwrap_or(1);(1..=5).map(|i|{let s=r["slots"].as_array().and_then(|a|a.iter().find(|s|s["id"]==i));let status=if let Some(s)=s{if i==active{"Current farm".into()}else{s["last_played"].as_str().unwrap_or("Saved").replace('T'," ").chars().take(16).collect()}}else{"Empty".into()};(format!("Farm {i}"),status)}).collect()}
pub fn process(env:&mut Environment)->bool{if std::env::var_os("ZF_DESKTOP").is_none()||env.bundle.bundle_identifier()!="com.playforge.ZombieFarm"||BUSY.swap(true,Ordering::Relaxed){return false}struct Guard;impl Drop for Guard{fn drop(&mut self){BUSY.store(false,Ordering::Relaxed);}}let _guard=Guard;let action=pending().lock().unwrap().take();let Some(action)=action else{return false};match perform(env,&action){Ok(exit)=>exit,Err(e)=>{crate::desktop_mods::session_message(&e);false}}}
fn perform(env:&mut Environment,action:&str)->Result<bool,String>{let r=registry();let from=r["active"].as_u64().ok_or("Farm index unavailable. Nothing was changed.")?;if action.starts_with("load"){let n=action[4..].parse::<u64>().map_err(|_|"Invalid farm")?;if !r["slots"].as_array().is_some_and(|s|s.iter().any(|s|s["id"]==n)){return Err("That slot is empty. Use New Game to create a farm.".into())}if n==from{crate::desktop_mods::session_message("This farm is already loaded.");return Ok(false)}}if action=="new"&&r["slots"].as_array().map_or(true,|s|s.len()>=5){return Err("All 5 farm slots are occupied. No farm was replaced.".into())}let director:id=msg_class![env;CCDirector sharedDirector];let scene:id=msg![env;director runningScene];let class=if scene==nil{String::new()}else{let c=crate::objc::ObjC::read_isa(scene,&env.mem);env.objc.try_get_class_name(c).unwrap_or("").to_owned()};let farm=class=="ZFFarmGameScene";if !class.is_empty()&&!farm{return Err("Return to your own farm before changing saves.".into())}if farm{let state:id=msg_class![env;GameState gameState];let code:i32=msg![env;state state];if code!=0{return Err("Finish the invasion or return home before changing saves.".into())}let _:()=msg![env;state saveGame];}if action=="save"&&!farm{return Err("Open your farm before saving.".into())}crate::desktop_mods::persist_session()?;crate::desktop_mods::backup_saves()?;if action=="save"{crate::desktop_mods::session_message("Farm saved and backed up.");return Ok(false)}let(operation,target)=if action=="new"{("new",0)}else{("load",action[4..].parse::<u64>().map_err(|_|"Invalid farm")?)};crate::desktop_mods::atomic(&root().join("switch-request.json"),&serde_json::to_vec(&json!({"schema":1,"from":from,"operation":operation,"target":target})).map_err(|e|e.to_string())?)?;Ok(true)}
