// Farm slots are isolated save roots. Existing UserData is always slot 1.
package main
import("encoding/json";"errors";"fmt";"os";"path/filepath";"time")
const maxFarmSlots=5
type FarmSlot struct { ID int `json:"id"`; Name string `json:"name"`; Created string `json:"created"`; LastPlayed string `json:"last_played"` }
type Farms struct { Schema int `json:"schema"`; Active int `json:"active"`; Slots []FarmSlot `json:"slots"` }
type SwitchRequest struct { Schema int `json:"schema"`; From int `json:"from"`; Operation string `json:"operation"`; Target int `json:"target"` }
func farmData(root string,id int)(string,error){if id<1||id>maxFarmSlots{return "",errors.New("invalid farm slot")};if id==1{return filepath.Join(root,"UserData"),nil};return filepath.Join(root,"Farms",fmt.Sprintf("farm-%02d",id),"UserData"),nil}
func(f Farms)has(id int)bool{for _,s:=range f.Slots{if s.ID==id{return true}};return false}
func(f Farms)validate()error{if f.Schema!=1||len(f.Slots)<1||len(f.Slots)>maxFarmSlots||!f.has(f.Active){return errors.New("invalid farm index; no save files were changed")};seen:=map[int]bool{};for _,s:=range f.Slots{if s.ID<1||s.ID>maxFarmSlots||seen[s.ID]||s.Name==""{return errors.New("invalid or duplicate farm slot")};seen[s.ID]=true};return nil}
func writeFarms(root string,f Farms)error{if e:=f.validate();e!=nil{return e};b,e:=json.MarshalIndent(f,"","  ");if e!=nil{return e};p:=filepath.Join(root,"farms.json");tmp,e:=os.CreateTemp(root,".farms-");if e!=nil{return e};n:=tmp.Name();defer os.Remove(n);if _,e=tmp.Write(b);e!=nil{tmp.Close();return e};if e=tmp.Sync();e!=nil{tmp.Close();return e};if e=tmp.Close();e!=nil{return e};if old,err:=os.ReadFile(p);err==nil{if err=os.WriteFile(p+".previous",old,0600);err!=nil{return err}};return os.Rename(n,p)}
func readFarms(root string)(Farms,error){var f Farms;b,e:=os.ReadFile(filepath.Join(root,"farms.json"));if os.IsNotExist(e){now:=time.Now().UTC().Format(time.RFC3339);f=Farms{1,1,[]FarmSlot{{1,"Farm 1",now,now}}};return f,writeFarms(root,f)};if e!=nil{return f,e};if e=json.Unmarshal(b,&f);e!=nil{return f,fmt.Errorf("farm index is unreadable; your saves were left intact: %w",e)};return f,f.validate()}
func applySwitch(root string,f Farms,q SwitchRequest)(Farms,error){if q.Schema!=1||q.From!=f.Active{return f,errors.New("stale or invalid farm switch request")};next:=f;next.Slots=append([]FarmSlot(nil),f.Slots...);switch q.Operation{case "new":id:=0;for n:=1;n<=maxFarmSlots;n++{if !f.has(n){p,_:=farmData(root,n);if _,e:=os.Stat(filepath.Dir(p));!os.IsNotExist(e){continue};id=n;break}};if id==0{return f,errors.New("all five farm slots are occupied; no farm was overwritten")};p,_:=farmData(root,id);if e:=os.MkdirAll(p,0700);e!=nil{return f,e};now:=time.Now().UTC().Format(time.RFC3339);next.Slots=append(next.Slots,FarmSlot{id,fmt.Sprintf("Farm %d",id),now,now});next.Active=id;case "load":if !f.has(q.Target){return f,errors.New("that farm slot does not exist")};p,_:=farmData(root,q.Target);if st,e:=os.Stat(p);e!=nil||!st.IsDir(){return f,errors.New("saved farm folder is missing; current farm was not replaced")};next.Active=q.Target;default:return f,errors.New("unknown farm operation")};if e:=writeFarms(root,next);e!=nil{return f,e};return next,nil}
func consumeSwitch(root string,f Farms)(Farms,bool,error){p:=filepath.Join(root,"switch-request.json");b,e:=os.ReadFile(p);if os.IsNotExist(e){return f,false,nil};if e!=nil{return f,false,e};if e=os.Rename(p,p+".handled");e!=nil{return f,false,e};var q SwitchRequest;if e=json.Unmarshal(b,&q);e!=nil{return f,false,e};next,e:=applySwitch(root,f,q);return next,e==nil,e}
