package main
import("os";"path/filepath";"testing";"encoding/json")
func TestFarmLegacyPreservation(t *testing.T){r:=t.TempDir();p,_:=farmData(r,1);os.MkdirAll(p,0700);os.WriteFile(filepath.Join(p,"old.save"),[]byte("original farm"),0600);f,e:=readFarms(r);if e!=nil{t.Fatal(e)};if f.Active!=1{t.Fatal(f)};f,e=applySwitch(r,f,SwitchRequest{1,1,"new",0});if e!=nil||f.Active!=2{t.Fatal(f,e)};b,_:=os.ReadFile(filepath.Join(p,"old.save"));if string(b)!="original farm"{t.Fatal("legacy save changed")};np,_:=farmData(r,2);if _,e:=os.Stat(filepath.Join(np,"old.save"));!os.IsNotExist(e){t.Fatal("new game inherited old data")};f,e=applySwitch(r,f,SwitchRequest{1,2,"load",1});if e!=nil||f.Active!=1{t.Fatal(f,e)}}
func TestFiveFarmsNeverOverwrite(t *testing.T){r:=t.TempDir();f,e:=readFarms(r);if e!=nil{t.Fatal(e)};p,_:=farmData(r,1);os.MkdirAll(p,0700);for i:=2;i<=5;i++{f,e=applySwitch(r,f,SwitchRequest{1,f.Active,"new",0});if e!=nil||f.Active!=i{t.Fatal(f,e)}};b,_:=os.ReadFile(filepath.Join(r,"farms.json"));_,e=applySwitch(r,f,SwitchRequest{1,5,"new",0});if e==nil{t.Fatal("overwrote full farm slots")};after,_:=os.ReadFile(filepath.Join(r,"farms.json"));if string(b)!=string(after){t.Fatal("changed full index")}}
func TestInvalidFarmRequests(t *testing.T){r:=t.TempDir();f,_:=readFarms(r);for _,q:=range []SwitchRequest{{2,1,"new",0},{1,2,"new",0},{1,1,"load",9},{1,1,"erase",1}}{if _,e:=applySwitch(r,f,q);e==nil{t.Fatal(q)}};for _,n:=range []int{-1,0,6,999}{if _,e:=farmData(r,n);e==nil{t.Fatal(n)}}}
func TestCorruptIndexNeverResets(t *testing.T){r:=t.TempDir();p:=filepath.Join(r,"farms.json");os.WriteFile(p,[]byte("broken"),0600);if _,e:=readFarms(r);e==nil{t.Fatal("silently reset corrupt index")};b,_:=os.ReadFile(p);if string(b)!="broken"{t.Fatal("overwritten")}}
func TestFarmIsolationAndRepeatedLoad(t *testing.T){r:=t.TempDir();f,_:=readFarms(r);p,_:=farmData(r,1);os.MkdirAll(p,0700);os.WriteFile(filepath.Join(p,"clock.json"),[]byte("farm one time"),0600);f,_=applySwitch(r,f,SwitchRequest{1,1,"new",0});p2,_:=farmData(r,2);os.WriteFile(filepath.Join(p2,"clock.json"),[]byte("farm two time"),0600);for i:=0;i<20;i++{target:=1+i%2;var e error;f,e=applySwitch(r,f,SwitchRequest{1,f.Active,"load",target});if e!=nil{t.Fatal(e)}};a,_:=os.ReadFile(filepath.Join(p,"clock.json"));b,_:=os.ReadFile(filepath.Join(p2,"clock.json"));if string(a)!="farm one time"||string(b)!="farm two time"{t.Fatal("cross-farm clock overwrite")}}
func TestRequestConsumedOnce(t *testing.T){r:=t.TempDir();f,_:=readFarms(r);b,_:=json.Marshal(SwitchRequest{1,1,"new",0});os.WriteFile(filepath.Join(r,"switch-request.json"),b,0600);f,again,e:=consumeSwitch(r,f);if e!=nil||!again{t.Fatal(e)};_,again,e=consumeSwitch(r,f);if e!=nil||again{t.Fatal("request replayed")}}
func TestDuplicateIndexRefused(t *testing.T){f:=Farms{1,1,[]FarmSlot{{ID:1,Name:"a"},{ID:1,Name:"b"}}};if f.validate()==nil{t.Fatal("duplicates accepted")}}
func TestMissingLoadFolderRefused(t *testing.T){r:=t.TempDir();f,_:=readFarms(r);f,_=applySwitch(r,f,SwitchRequest{1,1,"new",0});p,_:=farmData(r,1);os.RemoveAll(p);_,e:=applySwitch(r,f,SwitchRequest{1,2,"load",1});if e==nil{t.Fatal("loaded missing save folder")}}
