package main
import("encoding/json";"errors";"fmt";"os";"path/filepath";"strconv";"strings")
type FarmSlot struct { ID string `json:"id"`; Label string `json:"label"` }
type SaveIndex struct { Schema int `json:"schema"`; Active string `json:"active"`; Slots []FarmSlot `json:"slots"` }
type SwitchRequest struct { Op string `json:"op"`; Slot string `json:"slot"`; From string `json:"from"` }
func validSlot(id string) bool {if id=="original"{return true};if !strings.HasPrefix(id,"farm-"){return false};n,e:=strconv.Atoi(strings.TrimPrefix(id,"farm-"));return e==nil&&n>=2&&n<=1000000&&id==fmt.Sprintf("farm-%d",n)}
func slotDir(root,id string)(string,error){if !validSlot(id){return "",errors.New("invalid save identifier")};if id=="original"{return filepath.Join(root,"UserData"),nil};return filepath.Join(root,"Farms",id),nil}
func writeIndex(root string,idx SaveIndex)error{b,e:=json.MarshalIndent(idx,"","  ");if e!=nil{return e};p:=filepath.Join(root,"save-index.json");tmp:=p+".pending";f,e:=os.OpenFile(tmp,os.O_CREATE|os.O_TRUNC|os.O_WRONLY,0600);if e!=nil{return e};if _,e=f.Write(b);e==nil{e=f.Sync()};ce:=f.Close();if e!=nil{return e};if ce!=nil{return ce};return os.Rename(tmp,p)}
func loadIndex(root string)(SaveIndex,error){var idx SaveIndex;p:=filepath.Join(root,"save-index.json");b,e:=os.ReadFile(p);if os.IsNotExist(e){idx=SaveIndex{1,"original",[]FarmSlot{{"original","Farm 1 (original)"}}};return idx,writeIndex(root,idx)};if e!=nil{return idx,e};if e=json.Unmarshal(b,&idx);e!=nil{return idx,fmt.Errorf("save catalog is damaged; existing farms were not changed: %w",e)};if idx.Schema!=1||len(idx.Slots)==0||len(idx.Slots)>1000000{return idx,errors.New("unsupported save catalog")};seen:=map[string]bool{};for _,s:=range idx.Slots{if !validSlot(s.ID)||seen[s.ID]{return idx,errors.New("invalid or duplicate save catalog entry")};seen[s.ID]=true};if !seen[idx.Active]{return idx,errors.New("active farm missing from catalog")};return idx,nil}
func switchFarm(root string,idx SaveIndex,req SwitchRequest)(SaveIndex,error){
 if req.From!=idx.Active{return idx,errors.New("stale save request refused")}
 if req.Op=="load"{found:=false;for _,s:=range idx.Slots{if s.ID==req.Slot{found=true}};if !found{return idx,errors.New("selected save does not exist")};p,e:=slotDir(root,req.Slot);if e!=nil{return idx,e};if st,e:=os.Stat(p);e!=nil||!st.IsDir(){return idx,errors.New("selected farm folder is missing; current farm kept")};idx.Active=req.Slot
 }else if req.Op=="new"{n:=2;for _,s:=range idx.Slots{if strings.HasPrefix(s.ID,"farm-"){k,_:=strconv.Atoi(s.ID[5:]);if k>=n{n=k+1}}};var id,p string;for ;n<1000000;n++{id=fmt.Sprintf("farm-%d",n);p,_=slotDir(root,id);e:=os.MkdirAll(filepath.Dir(p),0700);if e!=nil{return idx,e};e=os.Mkdir(p,0700);if os.IsExist(e){continue};if e!=nil{return idx,e};break};if n>=1000000{return idx,errors.New("save library is full")};idx.Slots=append(idx.Slots,FarmSlot{id,fmt.Sprintf("Farm %d",n)});idx.Active=id
 }else{return idx,errors.New("unknown save action")};if e:=writeIndex(root,idx);e!=nil{return idx,e};return idx,nil
}
func consumeSwitch(root string,idx SaveIndex)(SaveIndex,error){p:=filepath.Join(root,"save-switch.json");b,e:=os.ReadFile(p);if e!=nil{return idx,e};var req SwitchRequest;if e=json.Unmarshal(b,&req);e!=nil{return idx,e};next,e:=switchFarm(root,idx,req);if e!=nil{return idx,e};if e=os.Remove(p);e!=nil{return next,e};return next,nil}
