// Zombie Farm desktop extension layer. MPL-2.0.
// Original ARM executable untouched. Audio/render scheduling remains real time.
use std::{cell::RefCell,collections::HashMap,fs,io::{Read,Write},path::{Path,PathBuf},sync::{Mutex,OnceLock},time::{Duration,Instant,SystemTime}};
use serde::{Deserialize,Serialize};
use sdl2::event::Event;
use sdl2::keyboard::Keycode;
use sdl2::mouse::MouseButton;
use touchHLE_gl_bindings::gl21compat as gl;
#[derive(Clone,Serialize,Deserialize)] #[serde(default)]
pub struct Settings {pub schema:u32,pub sandbox:bool,pub rate:u32,pub free_shop:bool,pub normalize:bool,pub profile:u8,pub tab_x:f32,pub tab_y:f32}
impl Default for Settings {fn default()->Self{Self{schema:1,sandbox:false,rate:1,free_shop:false,normalize:false,profile:0,tab_x:0.86,tab_y:0.28}}}
impl Settings {fn sanitize(&mut self){if ![1,2,5,10].contains(&self.rate){self.rate=1;}self.profile=self.profile.min(3);if !self.tab_x.is_finite(){self.tab_x=0.86}if !self.tab_y.is_finite(){self.tab_y=0.28}self.tab_x=self.tab_x.clamp(0.,0.94);self.tab_y=self.tab_y.clamp(0.,0.9);}fn effective_rate(&self)->f64{if self.sandbox{self.rate as f64}else{1.}}}
#[derive(Serialize,Deserialize,Default)] #[serde(default)]
struct ClockSave {schema:u32,extra_seconds:f64,last_guest_seconds:f64}
#[derive(Clone,Debug)] struct Clock {guest:f64,real:Instant,rate:f64}
impl Clock {fn value(&self)->f64{self.guest+self.real.elapsed().as_secs_f64()*self.rate}fn change(&mut self,rate:f64){self.guest=self.value();self.real=Instant::now();self.rate=rate;}}
struct State {settings:Settings,clock:Clock,open:bool,page:u8,crop:usize,message:String,last_persist:Instant,down:Option<(f32,f32)>,dragged:bool,consume_up:bool}
static STATE:OnceLock<Mutex<State>>=OnceLock::new();
fn unix()->f64{SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default().as_secs_f64()}
pub fn data_dir()->PathBuf{std::env::var_os("ZF_USER_DATA").map(PathBuf::from).unwrap_or_else(||PathBuf::from("UserData"))}
fn atomic(path:&Path,bytes:&[u8])->Result<(),String>{if let Some(p)=path.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?;}let temp=path.with_extension("pending");let mut f=fs::File::create(&temp).map_err(|e|e.to_string())?;f.write_all(bytes).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())?;drop(f);fs::rename(temp,path).map_err(|e|e.to_string())}
fn state()->&'static Mutex<State>{STATE.get_or_init(||{let mut settings:Settings=fs::read(data_dir().join("settings.json")).ok().and_then(|b|serde_json::from_slice(&b).ok()).unwrap_or_default();settings.sanitize();let saved:ClockSave=fs::read(data_dir().join("clock.json")).ok().and_then(|b|serde_json::from_slice(&b).ok()).unwrap_or_default();let extra=if saved.extra_seconds.is_finite(){saved.extra_seconds.clamp(0.,100.*365.*86400.)}else{0.};let guest=(unix()+extra).max(if saved.last_guest_seconds.is_finite(){saved.last_guest_seconds}else{0.});let rate=settings.effective_rate();Mutex::new(State{settings,clock:Clock{guest,real:Instant::now(),rate},open:false,page:0,crop:0,message:String::new(),last_persist:Instant::now(),down:None,dragged:false,consume_up:false})})}
fn persist(s:&mut State)->Result<(),String>{let guest=s.clock.value();let clock=ClockSave{schema:1,extra_seconds:(guest-unix()).max(0.),last_guest_seconds:guest};atomic(&data_dir().join("settings.json"),&serde_json::to_vec_pretty(&s.settings).map_err(|e|e.to_string())?)?;atomic(&data_dir().join("clock.json"),&serde_json::to_vec_pretty(&clock).map_err(|e|e.to_string())?)?;s.last_persist=Instant::now();Ok(())}
pub fn shutdown(){if let Ok(mut s)=state().lock(){let _=persist(&mut s);}}
pub fn game_time(original:SystemTime)->SystemTime{if std::env::var_os("ZF_DESKTOP").is_none(){return original;}let s=state().lock().unwrap();SystemTime::UNIX_EPOCH+Duration::from_secs_f64(s.clock.value().clamp(0.,4_000_000_000.))}
fn backup_saves()->Result<(),String>{let root=data_dir().join("touchHLE_sandbox");if !root.exists(){return Ok(())}let dest=data_dir().join("backups").join(format!("before-sandbox-{}.zip",(unix()*1000.)as u64));fs::create_dir_all(dest.parent().unwrap()).map_err(|e|e.to_string())?;let f=fs::File::create(dest).map_err(|e|e.to_string())?;let mut zip=zip::ZipWriter::new(f);fn walk(z:&mut zip::ZipWriter<fs::File>,root:&Path,p:&Path,total:&mut u64)->Result<(),String>{for e in fs::read_dir(p).map_err(|e|e.to_string())?{let e=e.map_err(|e|e.to_string())?;let t=e.file_type().map_err(|e|e.to_string())?;if t.is_symlink(){continue}if t.is_dir(){walk(z,root,&e.path(),total)?}else if t.is_file(){let bytes=fs::read(e.path()).map_err(|e|e.to_string())?;*total+=bytes.len()as u64;if *total>128*1024*1024{return Err("Save backup is too large".into())}let name=e.path().strip_prefix(root).unwrap().to_string_lossy().replace('\\',"/");z.start_file(name,zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Deflated)).map_err(|e|e.to_string())?;z.write_all(&bytes).map_err(|e|e.to_string())?;}}Ok(())}walk(&mut zip,&root,&root,&mut 0)?;zip.finish().map_err(|e|e.to_string())?;Ok(())}
/// Reversible resource changes before startup; game saves and the ARM executable are not edited.
pub fn prepare()->Result<(),String>{if std::env::var_os("ZF_DESKTOP").is_none(){return Ok(())}fs::create_dir_all(data_dir()).map_err(|e|e.to_string())?;let settings=state().lock().unwrap().settings.clone();let game=Path::new("Game/ZombieFarm.app");let src=Path::new("mods/original-Market.plist");if !game.exists()||!src.exists(){return Err("The bundled Zombie Farm content is incomplete".into())}let mut market=plist::Value::from_file(src).map_err(|e|e.to_string())?;let mut changes=0;if settings.sandbox&&settings.free_shop{if let Some(rows)=market.as_array_mut(){for row in rows{if let Some(d)=row.as_dictionary_mut(){let cat=d.get("category").and_then(|v|v.as_string()).unwrap_or("");if ["crop","item","upgrade","boost"].contains(&cat)&&d.contains_key("cost"){d.insert("cost".into(),plist::Value::Integer(0.into()));changes+=1;}}}}}let mut bytes=Vec::new();market.to_writer_binary(&mut bytes).map_err(|e|e.to_string())?;atomic(&game.join("Market.plist"),&bytes)?;let old=fs::read_to_string("Game/textures-applied.txt").unwrap_or_default();let key=format!("{}",settings.normalize);if old!=key{let name=if settings.normalize{"mods/textures-rgba.zip"}else{"mods/textures-original.zip"};let f=fs::File::open(name).map_err(|e|e.to_string())?;let mut archive=zip::ZipArchive::new(f).map_err(|e|e.to_string())?;for i in 0..archive.len(){let mut entry=archive.by_index(i).map_err(|e|e.to_string())?;let name=entry.enclosed_name().ok_or("Unsafe texture override path")?.to_owned();if name.components().count()!=1||name.extension().and_then(|s|s.to_str())!=Some("png"){return Err("Unexpected texture override".into())}let mut bytes=Vec::new();entry.read_to_end(&mut bytes).map_err(|e|e.to_string())?;atomic(&game.join(name),&bytes)?;}atomic(Path::new("Game/textures-applied.txt"),key.as_bytes())?;}atomic(&data_dir().join("last-launch.json"),format!("{{\"version\":\"0.12\",\"sandbox\":{},\"free_prices\":{},\"rate\":{},\"normalized_textures\":{}}}",settings.sandbox,changes,settings.effective_rate(),settings.normalize).as_bytes())?;Ok(())}
#[derive(Clone,Deserialize,Default)]struct Crop {name:String,stages:Vec<String>,notes:Vec<String>}
#[derive(Deserialize,Default)]struct Audit {png_checked:usize,flagged:usize,crops:Vec<Crop>,summary:Vec<String>}
static AUDIT:OnceLock<Audit>=OnceLock::new();fn audit()->&'static Audit{AUDIT.get_or_init(||fs::read("mods/crop-audit.json").ok().and_then(|b|serde_json::from_slice(&b).ok()).unwrap_or_default())}
fn fit(w:u32,h:u32)->(f32,f32,f32){let s=(((w as f32-24.)/400.).min((h as f32-24.)/454.)).min(1.8).max(0.2);((w as f32-400.*s)/2.,(h as f32-454.*s)/2.,s)}
fn tab(s:&Settings,w:u32,h:u32)->(f32,f32,f32){let sc=(h as f32/480.).clamp(0.8,1.6);((s.tab_x*w as f32).clamp(5.,(w as f32-62.*sc).max(5.)),(s.tab_y*h as f32).clamp(5.,(h as f32-48.*sc).max(5.)),sc)}
fn handle(s:&mut State,action:&str){s.message.clear();match action{"open"=>{s.open=true;s.page=0},"close"=>s.open=false,"back"=>s.page=0,"sandbox"=>s.page=1,"graphics"=>s.page=2,"display"=>s.page=3,"audit"=>s.page=4,"preview"=>s.page=5,"toggle"=>{if !s.settings.sandbox{if let Err(e)=backup_saves(){s.message=format!("Backup failed: {e}");return}}s.settings.sandbox=!s.settings.sandbox;s.clock.change(s.settings.effective_rate());s.message="Game clock updated immediately.".into();},"rate"=>{s.settings.rate=match s.settings.rate{1=>2,2=>5,5=>10,_=>1};s.clock.change(s.settings.effective_rate());s.message=if s.settings.sandbox{"Live clock changed; no restart needed."}else{"Enable sandbox to apply acceleration."}.into();},"free"=>{s.settings.free_shop=!s.settings.free_shop;s.message="Saved. Close and reopen to apply shop rules.".into();},"rgba"=>{s.settings.normalize=!s.settings.normalize;s.message="Saved. Close and reopen to apply textures.".into();},"inspect"=>{s.page=4;s.message=format!("{} PNGs checked; {} flagged references.",audit().png_checked,audit().flagged);},"nextcrop"=>{if !audit().crops.is_empty(){s.crop=(s.crop+1)%audit().crops.len();}},"report"=>{let _=fs::copy("mods/crop-audit.json",data_dir().join("crop-audit.json"));s.message="Report saved in your UserData folder.".into();},"repair"=>s.message="Original 1.17 sprites retained; flagged gaps reported.".into(),"profile0"=>s.settings.profile=0,"profile1"=>s.settings.profile=1,"profile2"=>s.settings.profile=2,"profile3"=>s.settings.profile=3,_=>{}}if let Err(e)=persist(s){s.message=format!("Settings were not saved: {e}");}}
fn row_actions(page:u8)->Vec<&'static str>{match page{1=>vec!["toggle","free","rate","report"],2=>vec!["rgba","inspect","report"],3=>vec!["profile0","profile1","profile2","profile3"],4=>vec!["preview","inspect","repair","report"],_=>vec!["sandbox","graphics","display","audit","close"]}}
/// Consume mod UI gestures so clicks never leak through to the farm.
pub fn event(e:&Event,window:&mut sdl2::video::Window)->bool{if std::env::var_os("ZF_DESKTOP").is_none(){return false}let(w,h)=window.size();let mut s=state().lock().unwrap();if let Event::Quit{..}=e{let _=persist(&mut s);return false}if let Event::KeyDown{keycode:Some(key),repeat:false,..}=e{match key{Keycode::F1=>{s.open=!s.open;s.page=0;return true},Keycode::Escape if s.open=>{s.open=false;return true},Keycode::F10=>{let mode=if window.fullscreen_state()==sdl2::video::FullscreenType::Off{sdl2::video::FullscreenType::Desktop}else{sdl2::video::FullscreenType::Off};let _=window.set_fullscreen(mode);return true},_=>{}}}match e{Event::MouseButtonDown{mouse_btn:MouseButton::Left,x,y,..}=>{let(tx,ty,sc)=tab(&s.settings,w,h);let hit=(*x as f32)>=tx&&(*x as f32)<tx+58.*sc&&(*y as f32)>=ty&&(*y as f32)<ty+42.*sc;if s.open||hit{s.down=Some((*x as f32,*y as f32));s.dragged=false;s.consume_up=true;return true}},Event::MouseMotion{x,y,..}=>{if let Some((dx,dy))=s.down{if !s.open&&(((*x as f32)-dx).abs()+((*y as f32)-dy).abs()>8.){s.dragged=true;s.settings.tab_x=((*x as f32)/w as f32).clamp(0.,0.9);s.settings.tab_y=((*y as f32)/h as f32).clamp(0.,0.88);}return true}if s.open{return true}},Event::MouseButtonUp{mouse_btn:MouseButton::Left,x,y,..}=>{if s.consume_up{s.consume_up=false;s.down=None;if s.dragged{let _=persist(&mut s);return true}if !s.open{handle(&mut s,"open");return true}let(px,py,sc)=fit(w,h);let x=(*x as f32-px)/sc;let y=(*y as f32-py)/sc;if x>=20.&&x<380.{if y>=412.&&y<=450.{if s.page==0{handle(&mut s,"close")}else{handle(&mut s,"back")}}else if s.page==5{if (325.0..=355.0).contains(&y){handle(&mut s,"nextcrop")}}else if (76.0..341.0).contains(&y){let row=((y-76.)/53.)as usize;let actions=row_actions(s.page);if (y-76.)%53.<=45.&&row<actions.len(){let action=actions[row];handle(&mut s,action);if action.starts_with("profile"){let dims=match s.settings.profile{1=>(1100,506),2=>(900,720),3=>(1160,426),_=>(960,640)};let _=window.set_size(dims.0,dims.1);}}}return true}},Event::MouseWheel{..}if s.open=>return true,_=>{}}s.open&&matches!(e,Event::MouseButtonDown{..}|Event::MouseButtonUp{..})}
#[derive(Clone)]struct Font {texture:String,chars:HashMap<u32,[i32;7]>,size:f32,base:f32}
impl Font{fn load(name:&str)->Self{let d=fs::read_to_string(format!("mods/ui/{name}.fnt")).unwrap_or_default();let mut f=Self{texture:format!("mods/ui/{name}.png"),chars:HashMap::new(),size:26.,base:26.};for l in d.lines(){let map:HashMap<&str,i32>=l.split_whitespace().filter_map(|a|{let(k,v)=a.split_once('=')?;Some((k,v.parse().ok()?))}).collect();if l.starts_with("info "){if let Some(v)=map.get("size"){f.size=v.abs()as f32;}}if l.starts_with("common "){if let Some(v)=map.get("base"){f.base=*v as f32;}}if l.starts_with("char "){if let Some(id)=map.get("id"){let mut g=[0;7];for(i,k)in["x","y","width","height","xoffset","yoffset","xadvance"].iter().enumerate(){g[i]=*map.get(k).unwrap_or(&0);}f.chars.insert(*id as u32,g);}}}f}fn width(&self,t:&str,size:f32)->f32{t.chars().map(|c|self.chars.get(&(c as u32)).map(|v|v[6]).unwrap_or(10)as f32).sum::<f32>()*size/self.size}}
struct Graphics {context:usize,textures:HashMap<String,(u32,u32,u32)>,dark:Font,light:Font}
thread_local!{static GRAPHICS:RefCell<Graphics>=RefCell::new(Graphics{context:0,textures:HashMap::new(),dark:Font::load("ABD26"),light:Font::load("ATWBD26")});}
impl Graphics{unsafe fn texture(&mut self,name:&str)->Option<(u32,u32,u32)>{if let Some(v)=self.textures.get(name){return Some(*v)}let b=fs::read(name).ok()?;let img=crate::image::Image::from_bytes(&b).ok()?;let(w,h)=img.dimensions();let mut tex=0;gl::GenTextures(1,&mut tex);gl::BindTexture(gl::TEXTURE_2D,tex);gl::TexParameteri(gl::TEXTURE_2D,gl::TEXTURE_MIN_FILTER,gl::LINEAR as i32);gl::TexParameteri(gl::TEXTURE_2D,gl::TEXTURE_MAG_FILTER,gl::LINEAR as i32);gl::TexParameteri(gl::TEXTURE_2D,gl::TEXTURE_WRAP_S,gl::CLAMP_TO_EDGE as i32);gl::TexParameteri(gl::TEXTURE_2D,gl::TEXTURE_WRAP_T,gl::CLAMP_TO_EDGE as i32);gl::PixelStorei(gl::UNPACK_ALIGNMENT,1);gl::TexImage2D(gl::TEXTURE_2D,0,gl::RGBA as i32,w as i32,h as i32,0,gl::RGBA,gl::UNSIGNED_BYTE,img.pixels().as_ptr()as*const _);let v=(tex,w,h);self.textures.insert(name.into(),v);Some(v)}unsafe fn image(&mut self,name:&str,x:f32,y:f32,w:f32,h:f32,alpha:f32){if let Some((t,_,_))=self.texture(name){gl::Enable(gl::TEXTURE_2D);gl::BindTexture(gl::TEXTURE_2D,t);gl::Color4f(alpha,alpha,alpha,alpha);quad(x,y,w,h,0.,0.,1.,1.);gl::Disable(gl::TEXTURE_2D);}}unsafe fn text(&mut self,t:&str,x:f32,y:f32,size:f32,light:bool){let f=if light{self.light.clone()}else{self.dark.clone()};if let Some((tex,w,h))=self.texture(&f.texture){gl::Enable(gl::TEXTURE_2D);gl::BindTexture(gl::TEXTURE_2D,tex);gl::Color4f(1.,1.,1.,1.);let sc=size/f.size;let mut xx=x;for c in t.chars(){if let Some(g)=f.chars.get(&(c as u32)){if g[2]>0&&g[3]>0{quad(xx+g[4]as f32*sc,y+(g[5]as f32-f.base)*sc,g[2]as f32*sc,g[3]as f32*sc,g[0]as f32/w as f32,g[1]as f32/h as f32,(g[0]+g[2])as f32/w as f32,(g[1]+g[3])as f32/h as f32);}xx+=g[6]as f32*sc;}}gl::Disable(gl::TEXTURE_2D);}}unsafe fn center(&mut self,t:&str,x:f32,y:f32,w:f32,size:f32,light:bool){let width=if light{self.light.width(t,size)}else{self.dark.width(t,size)};self.text(t,x+(w-width)/2.,y,size,light);}}
unsafe fn quad(x:f32,y:f32,w:f32,h:f32,u0:f32,v0:f32,u1:f32,v1:f32){gl::Begin(gl::QUADS);gl::TexCoord2f(u0,v0);gl::Vertex2f(x,y);gl::TexCoord2f(u1,v0);gl::Vertex2f(x+w,y);gl::TexCoord2f(u1,v1);gl::Vertex2f(x+w,y+h);gl::TexCoord2f(u0,v1);gl::Vertex2f(x,y+h);gl::End();}
unsafe fn rect(x:f32,y:f32,w:f32,h:f32,c:u32,r:f32){let a=((c>>24)&255)as f32/255.;gl::Color4f(((c>>16)&255)as f32/255.*a,((c>>8)&255)as f32/255.*a,(c&255)as f32/255.*a,a);if r<=0.{quad(x,y,w,h,0.,0.,1.,1.);return}let r=r.min(w/2.).min(h/2.);gl::Begin(gl::TRIANGLE_FAN);gl::Vertex2f(x+w/2.,y+h/2.);for i in 0..=32{let corner=(i/8).min(3);let angle=std::f32::consts::PI+(i as f32)*std::f32::consts::PI/16.;let(cx,cy)=match corner{0=>(x+r,y+r),1=>(x+w-r,y+r),2=>(x+w-r,y+h-r),_=>(x+r,y+h-r)};gl::Vertex2f(cx+r*angle.cos(),cy+r*angle.sin());}gl::End();}
fn rows(s:&State)->Vec<(String,String)>{let b=|v:bool|if v{"ON"}else{"OFF"}.to_string();match s.page{1=>vec![("Sandbox".into(),b(s.settings.sandbox)),("Free shopping".into(),b(s.settings.free_shop)),("Live game clock".into(),format!("{}x",s.settings.rate)),("Diagnostics".into(),"Save report".into())],2=>vec![("Texture decoding".into(),if s.settings.normalize{"Standard RGBA"}else{"Original"}.into()),("Inspect all crop stages".into(),"Tomatoes included".into()),("Graphics report".into(),"Save report".into())],3=>["Desktop / automatic","iPhone 16 Pro framing","Fold3 inner framing","Fold3 cover framing"].iter().enumerate().map(|(i,t)|(t.to_string(),if i==s.settings.profile as usize{"Selected"}else{""}.into())).collect(),4=>vec![("Preview original crops".into(),"Tomatoes first".into()),("Run crop inspection".into(),format!("{} flags",audit().flagged)),("Original asset recovery".into(),"Read report".into()),("Save full report".into(),"JSON".into())],_=>vec![("Sandbox".into(),"Clock & shop".into()),("Graphics".into(),"Original artwork".into()),("Screen fit".into(),"Desktop & phone".into()),("Crop inspector".into(),format!("{} flags",audit().flagged)),("Return to farm".into(),"".into())]}}
/// Real native overlay on the game's SDL backbuffer. Restore all GL state before returning.
pub fn draw(window:&sdl2::video::Window){if std::env::var_os("ZF_DESKTOP").is_none()||!gl::Begin::is_loaded(){return}let(w,h)=window.drawable_size();if w==0||h==0{return}let mut s=state().lock().unwrap();if s.last_persist.elapsed()>Duration::from_secs(1){let _=persist(&mut s);let line=format!("{:.6},{:.6},{:.0}\n",unix(),s.clock.value(),s.clock.rate);if let Ok(mut f)=fs::OpenOptions::new().append(true).create(true).open(data_dir().join("clock-samples.csv")){let _=f.write_all(line.as_bytes());}}
GRAPHICS.with(|cell|{let mut g=cell.borrow_mut();unsafe{let context=sdl2_sys::SDL_GL_GetCurrentContext()as usize;if context!=g.context{g.context=context;g.textures.clear();}let mut mode=0;let mut program=0;let mut active=0;gl::GetIntegerv(gl::MATRIX_MODE,&mut mode);gl::GetIntegerv(gl::CURRENT_PROGRAM,&mut program);gl::GetIntegerv(gl::ACTIVE_TEXTURE,&mut active);gl::PushAttrib(gl::ALL_ATTRIB_BITS);gl::PushClientAttrib(gl::CLIENT_ALL_ATTRIB_BITS);gl::UseProgram(0);gl::ActiveTexture(gl::TEXTURE1);gl::Disable(gl::TEXTURE_2D);gl::ActiveTexture(gl::TEXTURE0);gl::Disable(gl::TEXTURE_2D);gl::MatrixMode(gl::TEXTURE);gl::PushMatrix();gl::LoadIdentity();gl::MatrixMode(gl::PROJECTION);gl::PushMatrix();gl::LoadIdentity();gl::Ortho(0.,w as f64,h as f64,0.,-1.,1.);gl::MatrixMode(gl::MODELVIEW);gl::PushMatrix();gl::LoadIdentity();gl::Viewport(0,0,w as i32,h as i32);for cap in[gl::DEPTH_TEST,gl::STENCIL_TEST,gl::SCISSOR_TEST,gl::CULL_FACE,gl::LIGHTING,gl::FOG,gl::ALPHA_TEST]{gl::Disable(cap)}gl::Enable(gl::BLEND);gl::BlendFunc(gl::ONE,gl::ONE_MINUS_SRC_ALPHA);gl::TexEnvi(gl::TEXTURE_ENV,gl::TEXTURE_ENV_MODE,gl::MODULATE as i32);
if !s.open{let(tx,ty,sc)=tab(&s.settings,w,h);gl::Translatef(tx,ty,0.);gl::Scalef(sc,sc,1.);rect(2.,3.,58.,42.,0x900c1308,12.);rect(0.,0.,58.,42.,0xff352314,12.);rect(2.,2.,54.,38.,0xff33511a,10.);rect(3.,3.,52.,32.,0xff618d32,9.);rect(12.,8.,34.,2.,0xffa2c754,0.);g.center("Tools",0.,28.,58.,17.,true);if s.settings.sandbox&&s.settings.rate!=1{g.center(&format!("{}x",s.settings.rate),0.,57.,58.,15.,true);}}
else{rect(0.,0.,w as f32,h as f32,0x9a101506,0.);let(x,y,sc)=fit(w,h);gl::Translatef(x,y,0.);gl::Scalef(sc,sc,1.);rect(6.,8.,400.,454.,0x900c1308,19.);rect(0.,0.,400.,454.,0xff352314,19.);rect(3.,3.,394.,448.,0xffa47943,17.);rect(7.,7.,386.,440.,0xffffecc1,13.);g.image("mods/ui/paper.png",11.,62.,378.,381.,0.16);rect(6.,6.,388.,53.,0xff33511a,13.);rect(10.,10.,380.,38.,0xff618d32,9.);g.center(["Farm settings","Sandbox","Graphics","Screen fit","Crop inspector","Crop preview"][s.page.min(5)as usize],40.,39.,320.,23.,true);rect(15.,20.,7.,7.,0xffd6c382,4.);rect(378.,20.,7.,7.,0xffd6c382,4.);
if s.page==5{if let Some(crop)=audit().crops.get(s.crop){g.center(&format!("{} ({}/{})",crop.name,s.crop+1,audit().crops.len()),20.,91.,360.,18.,false);for i in 0..3{let xx=22.+i as f32*121.;for yy in(0..176).step_by(14){for xxx in(0..112).step_by(14){rect(xx+xxx as f32,114.+yy as f32,(112-xxx).min(14)as f32,(176-yy).min(14)as f32,if(xxx/14+yy/14)%2==0{0xffc6bb92}else{0xffeee0b6},0.)}}if let Some(name)=crop.stages.get(i){if !name.is_empty(){let path=format!("mods/crops/{name}");if let Some((_,iw,ih))=g.texture(&path){let sc=(104./iw as f32).min(168./ih as f32);g.image(&path,xx+4.+(104.-iw as f32*sc)/2.,118.+(168.-ih as f32*sc)/2.,iw as f32*sc,ih as f32*sc,1.);}}else{g.center("Unavailable",xx,205.,112.,12.,false);}}g.center(["Seeded","Seedling","Harvestable"][i],xx,310.,112.,12.,false);}rect(75.,325.,250.,28.,0xff618d32,6.);g.center("NEXT CROP",75.,345.,250.,14.,true);}}
else{for(i,(label,value))in rows(&s).iter().enumerate(){let y=76.+i as f32*53.;rect(23.,y+3.,354.,45.,0xffa6884d,7.);rect(23.,y,354.,45.,0xffedd99c,7.);rect(32.,y+2.,336.,2.,0xfffff4d1,0.);let vw=g.dark.width(value,13.);let ls=15.0_f32.min((320.-vw)/g.dark.width(label,1.));g.text(label,35.,y+28.,ls,false);g.text(value,365.-vw,y+28.,13.,false);}}
let detail=if !s.message.is_empty(){s.message.clone()}else{match s.page{1=>format!("Active clock: {:.0}x. Changes apply to existing crops.\nShop changes need a restart. F10: fullscreen.\nAcceleration affects all date-based game timers.",s.clock.rate),2=>"Original pixels retained. No AI replacements.\nTexture changes apply after closing and reopening.\nReports list missing references, not invented fixes.".into(),3=>"Aspect-fit only: no stretched art or cropped buttons.\nDrag window edges to resize. F10: fullscreen.".into(),4=>format!("{} original PNGs decoded; {} flagged references.\nRead-only sprite and growth-chain inspection.\nReports are stored beside your save backups.",audit().png_checked,audit().flagged),5=>"Actual original sprites on a transparency grid.\nMissing stages are reported, never fabricated.".into(),_=>"Original game with optional local controls.\nDrag the green tab to move it. F1: open Tools.\nWindows desktop build 0.12".into()}};for(i,line)in detail.lines().take(3).enumerate(){let size=12.0_f32.min(350./g.dark.width(line,1.).max(1.));g.text(line,25.,365.+i as f32*16.,size,false);}g.center(if s.page==0{"CLOSE"}else{"BACK"},30.,436.,340.,14.,false);}
gl::MatrixMode(gl::MODELVIEW);gl::PopMatrix();gl::MatrixMode(gl::PROJECTION);gl::PopMatrix();gl::MatrixMode(gl::TEXTURE);gl::PopMatrix();gl::MatrixMode(mode as u32);gl::PopClientAttrib();gl::PopAttrib();gl::ActiveTexture(active as u32);gl::UseProgram(program as u32);}});}
#[cfg(test)]mod tests{use super::*;#[test]fn settings_validation(){let mut s=Settings{rate:999,tab_x:f32::NAN,profile:99,..Settings::default()};s.sanitize();assert_eq!(s.rate,1);assert_eq!(s.profile,3);assert!(s.tab_x.is_finite());assert_eq!(s.effective_rate(),1.);}#[test]fn clock_switch_is_continuous(){let mut c=Clock{guest:1000.,real:Instant::now()-Duration::from_secs(2),rate:10.};let before=c.value();assert!((before-1020.).abs()<0.1);c.change(1.);assert!((c.value()-before).abs()<0.05);}#[test]fn panel_fits(){for(w,h)in[(960,640),(1100,506),(900,720),(1160,426),(320,240)]{let(x,y,s)=fit(w,h);assert!(x>=0.&&y>=0.);assert!(x+400.*s<=w as f32);assert!(y+454.*s<=h as f32);}}}
